# Generated by Django 4.2 on 2023-05-09 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('wikipedia', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField()),
                ('authors', models.ManyToManyField(related_name='authors', to='games.author')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='user@mail.com', max_length=50, unique=True)),
                ('password', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.ManyToManyField(related_name='wishlists', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('category', models.CharField(choices=[("Jeu de l'année", 'GAME_OF_THE_YEAR'), ("Jeu de l'année 'Enfant'", 'KID_GAME_OF_THE_YEAR'), ("Jeu de l'année 'Expert'", 'EXPERT_GAME_OF_THE_YEAR'), ("Jeu de l'année 'Initié'", 'NOOB_GAME_OF_THE_YEAR'), ('Prix du Jury', 'JURY_PRIZE'), ('Grand Prix', 'BIG_PRIZE')], max_length=50)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.AddConstraint(
            model_name='award',
            constraint=models.UniqueConstraint(fields=('category', 'year'), name='unique_award'),
        ),
    ]
