# Generated by Django 4.2 on 2023-05-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
    ]
